site_name: HyPyP Docs
site_url: https://hypyp.readthedocs.io/
repo_url: https://github.com/ppsp-team/HyPyP/

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.snippets:
      base_path: .
      check_paths: true

theme:
  name: "material"

extra_css:
  - custom.css

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

watch:
  - hypyp