# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='hypyp',
    version='0.2.0-alpha.5',
    description='The Hyperscanning Python Pipeline.',
    python_requires='==3.*,>=3.7.0',
    project_urls={
        "documentation": "https://hypyp.readthedocs.io",
        "homepage": "https://github.com/ppsp-team/HyPyP",
        "repository": "https://github.com/ppsp-team/HyPyP"
    },
    author='Anaël AYROLLLES',
    author_email='anael.ayrollles@pasteur.fr',
    maintainer='Florence BRUN',
    maintainer_email='florence.brun@pasteur.fr',
    license='BSD-3-Clause',
    keywords='hyperscanning neuroscience pipeline statistics visualization',
    classifiers=[
        'Development Status :: 3 - Alpha', 'Topic :: Scientific/Engineering',
        'License :: OSI Approved :: BSD License'
    ],
    packages=['hypyp', 'hypyp.ext.mpl3d'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'astropy==4.*,>=4.0.1', 'autoreject==0.*,>=0.2.1',
        'joblib==0.*,>=0.14.1', 'matplotlib==3.*,>=3.2.1',
        'meshio==4.*,>=4.0.13', 'mne==0.*,>=0.21.1', 'numpy==1.*,>=1.18.3',
        'pandas==1.*,>=1.0.3', 'pyqt5==5.*,>=5.15.0',
        'scikit-learn==0.*,>=0.22.2', 'scipy==1.*,>=1.4.1',
        'statsmodels==0.*,>=0.11.1', 'tqdm==4.*,>=4.46.0'
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0", "ipywidgets==7.*,>=7.5.1",
            "jupyterlab==2.*,>=2.1.4", "markdown-include==0.*,>=0.5.1",
            "mkdocs==1.*,>=1.1.0", "mkdocs-material==5.*,>=5.1.1",
            "mkdocstrings==0.*,>=0.10.3", "pylint==2.*,>=2.4.4",
            "pytest==5.*,>=5.4.1", "widgetsnbextension==3.*,>=3.5.1"
        ]
    },
)
