name: CI

on: [push, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self add poetry-plugin-shell
          poetry self add poetry-plugin-export
          poetry export -f requirements.txt -o requirements.txt --without-hashes --with dev
          poetry run pip install --upgrade pip
          poetry run pip install -q -r requirements.txt
          poetry install -q
      - name: Test with pytest
        run: |
          poetry run pytest tests/
